In [1]:
def ReadFileIntoList(testFile = False):
    filename = 'input.txt'
    if testFile:
        filename = 'test.txt'
    with open(filename) as file:
        lines = file.readlines()
        lines = [line.rstrip() for line in lines]
    return lines

In [2]:
import numpy as np

In [3]:
def GetSurroundingCells(row, col, rows,cols):
    changes = [(-1,0),(0,-1),(0,1),(1,0)]
    #changes = [(0,1),(1,0)]
    cells = []
    for dR,dC in changes:
        cellR = row + dR
        cellC = col + dC
        if 0<=cellR<rows and 0<=cellC<cols:
            cells.append((cellR,cellC))
    return cells

In [4]:
def CreateCaveRoutesDict(array, row, col, total = 0):
    rows = len(array)
    cols = len(array[0])
    posnToGoTo = GetSurroundingCells(row,col,rows, cols)
    totals = []
    for sRow,sCol in posnToGoTo:
        newTotal = total
        if sRow == rows - 1 and sCol == cols - 1:
            newTotal += array[sRow][sCol]
            return newTotal
        newTotal += array[sRow][sCol]
        result = CreateCaveRoutesDict(array, sRow, sCol, newTotal)
        if type(result)== list:
            totals.append(np.min(result))
        elif type(result) == int:
            totals.append(result)
        else:
            print("Result is not list of int! Panic!")
    return totals

In [35]:
def CreateArray(testFile = False):
    input = ReadFileIntoList(testFile)
    array = [[int(letter) for letter in line] for line in input]
    return np.array(array)

In [43]:
def CreateLargerArray(testFile = False, timesLarger = 5):
    input = ReadFileIntoList(testFile)
    array = [[int(letter) for letter in line] for line in input]
    rows = len(array)
    cols = len(array[0])
    largerArray = []
    for rowMultiplier in range(timesLarger):
        baseRow = rows * rowMultiplier
        for row in range(rows):
            largerArray.append([0] * (cols * timesLarger))
        for colMultiplier in range(timesLarger):
            baseCol = cols * colMultiplier
            for row in range(rows):
                for col in range(cols):
                    largerArray[baseRow + row][baseCol + col] = array[row][col]
                    if rowMultiplier > 0 or colMultiplier > 0:
                        sum = (array[row][col] + (rowMultiplier+colMultiplier)) % 9
                        if sum == 0:
                            sum = 9
                        largerArray[baseRow + row][baseCol + col] = sum
    return np.array(largerArray)

In [42]:
11 // 9

1

In [31]:
array = CreateLargerArray(True)

In [5]:
def CreateUnvistedArray(array):
    rows = len(array)
    cols = len(array[0])
    unvisitedArray = []
    for row in range(rows):
        unvisitedArray.append([False] * cols)
    return np.array(unvisitedArray)


In [33]:
def CreateDistanceArray(array):
    rows = len(array)
    cols = len(array[0])
    distanceArray = []
    for row in range(rows):
        distanceArray.append([np.inf] * cols)
    distanceArray[0][0] = 0
    return np.array(distanceArray)

In [17]:
CreateDistanceArray(array)

[[0, inf, inf, inf, inf, inf, inf, inf, inf, inf],
 [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
 [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
 [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
 [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
 [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
 [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
 [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
 [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
 [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf]]

In [10]:
array = CreateArray(True)
result = CreateCaveRoutesDict(array, 0, 0)
answer = np.min(result)
print("Answer is", answer)


Answer is 40


In [23]:
unvisitedSet = CreateUnvistedArray(array)
unvisitedSet[0][0] = True
if unvisitedSet[0][0]:
    print("Here")

Here


In [10]:
array = CreateArray(True)
unvisitedArray = CreateUnvistedArray(array)
distanceArray = CreateDistanceArray(array)

In [58]:
np.where(unvisitedSet == False)

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       dtype=int64),
 array([4, 5, 6, 7, 8, 9, 4, 5, 6, 7, 8, 9, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
        4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5,
        6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7,
        8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       dtype=int64))

In [9]:
np.where(unvisitedArray == False)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        9, 9, 9, 9, 9, 9, 9, 9, 9, 9], dtype=int64),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
        4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5,
        6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7,
        8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64))

In [15]:
array = CreateArray()
unvisitedArray = CreateUnvistedArray(array)
distanceArray = CreateDistanceArray(array)
rows = len(array)
cols = len(array[0])
destNodeRow = rows - 1
destNodeCol = cols - 1
cRow = 0
cCol = 0
reachedDest = False
visited = 0

while(not reachedDest):
    currentDistance = distanceArray[cRow][cCol]
    surroundingCells = GetSurroundingCells(cRow,cCol,rows, cols)
    smallestDistance = np.inf
    #print(f"Current node is ({cRow},{cCol})")
    for sRow,sCol in surroundingCells:
        if unvisitedArray[sRow][sCol]:
            continue
        edgeDistance = array[sRow][sCol]
        totalDistance = currentDistance + edgeDistance
        if totalDistance < distanceArray[sRow][sCol]:
            distanceArray[sRow][sCol] = totalDistance
    unvisitedArray[cRow][cCol] = True
    visited += 1
    #print(f"Visited {visited} nodes. {100-visited} to go ...")
    splitCoords = np.where(unvisitedArray == False)
    potentialCoords = list(zip(list(splitCoords[0]),list(splitCoords[1])))
    for pRow, pCol in potentialCoords:
        if distanceArray[pRow][pCol] < smallestDistance:
            smallestDistance = distanceArray[pRow][pCol]
            nRow = pRow
            nCol = pCol
    cRow = nRow
    cCol = nCol
    if unvisitedArray[destNodeRow][destNodeCol]:
        reachedDest = True
answer = distanceArray[destNodeRow][destNodeCol]
print("Answer is",answer)


Answer is 790


In [45]:
array = CreateLargerArray()
unvisitedArray = CreateUnvistedArray(array)
distanceArray = CreateDistanceArray(array)
rows = len(array)
cols = len(array[0])
destNodeRow = rows - 1
destNodeCol = cols - 1
cRow = 0
cCol = 0
reachedDest = False
visited = 0

while(not reachedDest):
    currentDistance = distanceArray[cRow][cCol]
    surroundingCells = GetSurroundingCells(cRow,cCol,rows, cols)
    smallestDistance = np.inf
    #print(f"Current node is ({cRow},{cCol})")
    for sRow,sCol in surroundingCells:
        if unvisitedArray[sRow][sCol]:
            continue
        edgeDistance = array[sRow][sCol]
        totalDistance = currentDistance + edgeDistance
        if totalDistance < distanceArray[sRow][sCol]:
            distanceArray[sRow][sCol] = totalDistance
    unvisitedArray[cRow][cCol] = True
    visited += 1
    #print(f"Visited {visited} nodes. {100-visited} to go ...")
    splitCoords = np.where(unvisitedArray == False)
    potentialCoords = list(zip(list(splitCoords[0]),list(splitCoords[1])))
    for pRow, pCol in potentialCoords:
        if distanceArray[pRow][pCol] < smallestDistance:
            smallestDistance = distanceArray[pRow][pCol]
            nRow = pRow
            nCol = pCol
    cRow = nRow
    cCol = nCol
    if unvisitedArray[destNodeRow][destNodeCol]:
        reachedDest = True
answer = distanceArray[destNodeRow][destNodeCol]
print("Answer is",answer)

In [44]:
unvisitedSet

{0: {0: True,
  1: True,
  2: True,
  3: True,
  4: False,
  5: False,
  6: False,
  7: False,
  8: False,
  9: False},
 1: {0: True,
  1: True,
  2: True,
  3: True,
  4: False,
  5: False,
  6: False,
  7: False,
  8: False,
  9: False},
 2: {0: True,
  1: True,
  2: True,
  3: True,
  4: False,
  5: False,
  6: False,
  7: False,
  8: False,
  9: False},
 3: {0: False,
  1: False,
  2: False,
  3: False,
  4: False,
  5: False,
  6: False,
  7: False,
  8: False,
  9: False},
 4: {0: False,
  1: False,
  2: False,
  3: False,
  4: False,
  5: False,
  6: False,
  7: False,
  8: False,
  9: False},
 5: {0: False,
  1: False,
  2: False,
  3: False,
  4: False,
  5: False,
  6: False,
  7: False,
  8: False,
  9: False},
 6: {0: False,
  1: False,
  2: False,
  3: False,
  4: False,
  5: False,
  6: False,
  7: False,
  8: False,
  9: False},
 7: {0: False,
  1: False,
  2: False,
  3: False,
  4: False,
  5: False,
  6: False,
  7: False,
  8: False,
  9: False},
 8: {0: False,
  1: 

In [14]:
from functools import reduce
from operator import concat
flatList = reduce(concat, result)

In [15]:
flatList

[[[[[[[[[[[[[[[[75]]]]]]]],
        [[[[[[[[80]]]]]]],
         [[[[[[[80]]]]]],
          [[[[[[78]]]]],
           [[[[[70]]]], [[[[72]]], [[[67]], [[69], [62, 69]]]]]]]]],
       [[[[[[[[[82]]]]]]],
         [[[[[[[82]]]]]],
          [[[[[[80]]]]],
           [[[[[72]]]], [[[[74]]], [[[69]], [[71], [64, 71]]]]]]]],
        [[[[[[[[78]]]]]],
          [[[[[[76]]]]],
           [[[[[68]]]], [[[[70]]], [[[65]], [[67], [60, 67]]]]]]],
         [[[[[[[79]]]]], [[[[[71]]]], [[[[73]]], [[[68]], [[70], [63, 70]]]]]],
          [[[[[[66]]]], [[[[68]]], [[[63]], [[65], [58, 65]]]]],
           [[[[[68]]], [[[63]], [[65], [58, 65]]]],
            [[[[64]], [[66], [59, 66]]],
             [[[70], [63, 70]], [[65, 72], [75]]]]]]]]]],
      [[[[[[[[[[78]]]]]]],
         [[[[[[[78]]]]]],
          [[[[[[76]]]]],
           [[[[[68]]]], [[[[70]]], [[[65]], [[67], [60, 67]]]]]]]],
        [[[[[[[[74]]]]]],
          [[[[[[72]]]]],
           [[[[[64]]]], [[[[66]]], [[[61]], [[63], [56, 63]]]]]]],
 